dsadd user cn=user1,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user1@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user2,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user2@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user3,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user3@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user4,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user4@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user5,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user5@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user6,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user6@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user7,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user7@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user8,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user8@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user9,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user9@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user10,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user10@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user11,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user11@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user12,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user12@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user13,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user13@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user14,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user14@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user15,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user15@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user16,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user16@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user17,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user17@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user18,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user18@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user19,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user19@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user20,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user20@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user21,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user21@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user22,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user22@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user23,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user23@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user24,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user24@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user25,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user25@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user26,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user26@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user27,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user27@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user28,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user28@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user29,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user29@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user30,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user30@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user31,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user31@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user32,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user32@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user33,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user33@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user34,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user34@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user35,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user35@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user36,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user36@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user37,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user37@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user38,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user38@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user39,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user39@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user40,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user40@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user41,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user41@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user42,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user42@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user43,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user43@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user44,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user44@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user45,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user45@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user46,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user46@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user47,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user47@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user48,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user48@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user49,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user49@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
dsadd user cn=user50,OU=IT,DC=company,DC=local -fn Fname -ln Lname -pwd P@$$w0rd -mustchpwd yes -upn user50@company.local -memberof cn=SysAdmins,OU=IT,DC=company,DC=local
pause